### ISSUE TITLE
Install from pypi failing

### ISSUE THREAD

**Issue by joezuntz** [alexarnimueller/som#11]
Hi there - thanks for making this available!

Installation with pip currently fails for me on MacOS 10.15.7 and python 3.6.13 with this error:
```
...
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
...
````

Installing directly from github works with:
```
pip install git+https://github.com/alexarnimueller/som
```

**Comment by alexarnimueller** [comment]
Hi

Sorry for that and thanks for letting me know.
Should be fixed now with v1.0.2

`pip install --upgrade som-pbc`

Cheers
