### ISSUE TITLE
How could I obtain the SOM neurons weight? (or called neurons center)

### ISSUE THREAD

**Issue by maso0310** [alexarnimueller/som#12]
Based on my understanding of how SOM works, I think there should be a weight values or called neurons center could be found, but i didn't find the related methods/functions in the document, how could I find it?

**Comment by alexarnimueller** [comment]
Hi! After training, the weights of the neurons are available in the attribute `map` of the `SOM` instance. The `map` has the shape `(x, y, len(data[0]))`, so for every feature of the input data, the neurons hold a weight.

**Comment by maso0310** [comment]
Oh , I got it. Thanks a lot.
