### ISSUE TITLE
May I know how to do prediction out of it please?

### ISSUE THREAD

**Issue by hanzigs** [alexarnimueller/som#4]
Hi, 
1. May I know a prediction function available?
2. In Creating dummy target values in the example, you have done 500 each, is that random, are can we do some kmeans before that and find the labels and assign that

**Comment by alexarnimueller** [comment]
what do you want to predict? If you have class labels for your dataset, you can get the closest neighboring data points for a new data point like this:
`get_neighbors(datapoint, data, labels, d=0)`
d sets how many neurons around the one of your datapoint should be considered.
