### ISSUE TITLE
How to change learning rate ??

### ISSUE THREAD

**Issue by andyresta** [alexarnimueller/som#8]
i want to change learning rate, where is this ??

**Comment by alexarnimueller** [comment]
I assume you mean alpha and/or sigma.
The initial alpha value can be set with `alpha_start` when the `SOM` is initiated.
i.e. `SOM(10, 10, alpha_start=0.6, seed=42)`

The decay of alpha and sigma can either be set as `linear` or `hill` in the `fit` function. Sigma is defined as half the size of `x` of the SOM.
